### ISSUE TITLE
ImportError: Import by filename is not supported, when running the command line python -m unittest on the script in 2.7

### ISSUE THREAD

**Issue by fdparan** [fdparan/python_kata#1]
I'm not quite sure as to why the command line unittest only works in Python 3 and not in 2.7. The stack trace is as follows.

> Traceback (most recent call last):
>   File "/Users/francisparan/anaconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/Users/francisparan/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/Users/francisparan/anaconda/lib/python2.7/unittest/__main__.py", line 12, in <module>
>     main(module=None)
>   File "/Users/francisparan/anaconda/lib/python2.7/unittest/main.py", line 94, in **init**
>     self.parseArgs(argv)
>   File "/Users/francisparan/anaconda/lib/python2.7/unittest/main.py", line 149, in parseArgs
>     self.createTests()
>   File "/Users/francisparan/anaconda/lib/python2.7/unittest/main.py", line 158, in createTests
>     self.module)
>   File "/Users/francisparan/anaconda/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
>     suites = [self.loadTestsFromName(name, module) for name in names]
>   File "/Users/francisparan/anaconda/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
>     module = **import**('.'.join(parts_copy))
> ImportError: Import by filename is not supported.

I highly suspect that this is the 2.7 interpreter trying to execute this import:

`from src import factorial`

but might it also be the fact that doing -m  option requires relative import of a module in the script?

**Comment by osmanpontes** [comment]
I'm experiencing the same issue.
@fdparan did you solve this?
